site_name: DiPPER2 documentation
site_url: https://thwacker.github.io/DiPPER2/
use_directory_urls: true
theme:
  name: "material"
font: false
nav:
  - Documentation: index.md
  - Reference: reference.md


plugins:
  - mkdocstrings
