site_name: DiPPER2 documentation
use_directory_urls: https://thwacker.github.io/DiPPER2/
theme:
  name: "material"
font: false
nav:
  - Documentation: index.md
  - Reference: reference.md


plugins:
  - mkdocstrings
